
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://rakeshpatil7496:Rakesh@signuplogin.e2qk6.mongodb.net/SignupLogin?retryWrites=true&w=majority
      - JWT_SECRET=RAKESH
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
